#! /bin/sh
PANEL_HEIGHT=25
BORDERSIZE=3
GAP=0
export PANEL_HEIGHT
export BORDERSIZE
export GAP
export _JAVA_AWT_WM_NONREPARENTING=1 # Fix java apps

bspc config top_padding $PANEL_HEIGHT 
bspc config window_gap  $GAP

# Various settings
bspc config gapless_monocle true # Default setup uses negative padding, and gapless monocle looks really weird like that
bspc config borderless_monocle  true
bspc config single_monocle true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
## Honor size hints: do not make windows smaller than they wish to be
#bspc config honor_size_hints true 

# Color settings
bspc config focused_border_color "#DEE1E6"
bspc config normal_border_color "#757575"
bspc config presel_feedback_color "#757575"

bspc config border_width $BORDERSIZE
bspc config window_gap $GAP

bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Settings for manual splitting
bspc config split_ratio         0.50

bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d • • • • • • • • • •

bspc rule -a screenkey --unmanage
bspc rule -a gcolor2 state=floating center=true
bspc rule -a spotify state=pseudo_tiled
bspc rule -a google-chrome-unstable private=on
bspc rule -a google-chrome-stable private=on
bspc rule -a chromium private=on
bspc rule -a firefox private=on
bspc rule -a wpa_gui state=pseudo_tiled

